---
kind: pipeline
type: docker
name: default
trigger:
  event:
    exclude:
      - pull_request

steps:
  - name: build
    image: node:13-buster-slim
    commands:
      - yarn global add gatsby-cli && gatsby telemetry --disable
      - yarn --production --frozen-lockfile --non-interactive
      - gatsby build
    environment:
      SANITY_PROJECT_ID:
        from_secret: SANITY_PROJECT_ID
      SANITY_DATASET:
        from_secret: SANITY_DATASET
      SANITY_TOKEN:
        from_secret: SANITY_TOKEN
      SANITY_GRAPHQL_TAG:
        from_secret: SANITY_GRAPHQL_TAG

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dgliwka/self
    when:
      branch:
        - master
